from .config import CfgNode as CN

_CN = CN()
_CN.VERSION = 2

# Model
_CN.ALGORITHM = "joint_waft"

_CN.WAFT = CN()
_CN.WAFT.FEATURE_ENCODER = CN()
_CN.WAFT.FEATURE_ENCODER.TYPE = "dav2"
_CN.WAFT.FEATURE_ENCODER.ARCH = "vits"
_CN.WAFT.FEATURE_ENCODER.LORA_RANK = 8
_CN.WAFT.FEATURE_ENCODER.LORA_ALPHA = 16
_CN.WAFT.MAX_DISP = 192
_CN.WAFT.LOSS = ["mixlap_64"]

_CN.WAFT.ITERATIVE_MODULE = CN()
_CN.WAFT.ITERATIVE_MODULE.TASK = ['delta'] * 8

_CN.WAFT.ITERATIVE_MODULE.PROP_ITER = CN()
_CN.WAFT.ITERATIVE_MODULE.PROP_ITER.TYPE = "vit"
_CN.WAFT.ITERATIVE_MODULE.PROP_ITER.ARCH = "vits"
_CN.WAFT.ITERATIVE_MODULE.PROP_ITER.LORA_RANK = 8
_CN.WAFT.ITERATIVE_MODULE.PROP_ITER.LORA_ALPHA = 16
_CN.WAFT.ITERATIVE_MODULE.PROP_ITER.PATCH_SIZE = 8

_CN.WAFT.ITERATIVE_MODULE.DELTA_ITER = CN()
_CN.WAFT.ITERATIVE_MODULE.DELTA_ITER.TYPE = "vit"
_CN.WAFT.ITERATIVE_MODULE.DELTA_ITER.ARCH = "vits"
_CN.WAFT.ITERATIVE_MODULE.DELTA_ITER.LORA_RANK = 8
_CN.WAFT.ITERATIVE_MODULE.DELTA_ITER.LORA_ALPHA = 16
_CN.WAFT.ITERATIVE_MODULE.DELTA_ITER.PATCH_SIZE = 8

# Joint Multi-Task Options
_CN.JOINT = CN()
_CN.JOINT.DISP_WEIGHT = 1.0
_CN.JOINT.FLOW_WEIGHT = 1.0
_CN.JOINT.CYCLE_WEIGHT = 0.1
_CN.JOINT.NUM_ITERS = 8

# Datasets
_CN.DATASETS = CN()
_CN.DATASETS.TRAIN = ["sceneflow"]
_CN.DATASETS.MUL = [-1]
_CN.DATASETS.TEST = ["things"]
_CN.DATASETS.IMG_GAMMA = None
_CN.DATASETS.SATURATION_RANGE = [0, 1.4]
_CN.DATASETS.DO_FLIP = False
_CN.DATASETS.SPATIAL_SCALE = [-0.2, 0.4]
_CN.DATASETS.YJITTER = False
_CN.DATASETS.CROP_SIZE = [368, 784]
_CN.DATASETS.DIVIS_BY = 16

# Dataloader
_CN.DATALOADER = CN()
_CN.DATALOADER.NUM_WORKERS = 4

# Solver
_CN.SOLVER = CN()
_CN.SOLVER.MIX_PRECISION = True
_CN.SOLVER.MAX_ITER = 300000
_CN.SOLVER.BASE_LR = 0.0005
_CN.SOLVER.CHECKPOINT_PERIOD = 20000
_CN.SOLVER.LATEST_CHECKPOINT_PERIOD = 1000
_CN.SOLVER.IMS_PER_BATCH = 4
_CN.SOLVER.GRAD_CLIP = 1.0
_CN.SOLVER.RESUME = None
_CN.SOLVER.NO_RESUME_OPTIMIZER = False
_CN.SOLVER.MAX_DISP = 192
_CN.SOLVER.LOSS_TYPE = "JointL1"

# Test
_CN.TEST = CN()
_CN.TEST.EVAL_PERIOD = 10000
_CN.TEST.EVAL_THRESH = [['1.0', '3.0']]
_CN.TEST.EVAL_MAX_DISP = [1000]
_CN.TEST.EVAL_ONLY_VALID = [True]

_CN.CUDNN_BENCHMARK = True

def export_model_config(cfg: CN) -> CN:
    model_config = CN()
    fields = ["ALGORITHM", "WAFT", "JOINT"]
    for fld in fields:
        if hasattr(cfg, fld):
            setattr(model_config, fld, getattr(cfg, fld))
    return model_config.clone()
